name: Check YAML Changes

on:
  push:
    branches:
    - main

jobs:
  check_yaml_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GITHUB_REF
        run: echo "GITHUB_REF:${{ github.ref }}"
        
      - name: Make script executable
        run: chmod +x script.sh

      - name: Run Script
        run: ./script.sh
