name: PR Comparison Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  compare-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display PR branch name
        run: echo "PR branch is ${{ github.head_ref }}"

      - name: Compare code changes
        run: |
          # Assuming the main branch is 'main' (replace with your branch name)
          MAIN_BRANCH="main"

          # Use 'git diff' to compare code changes
          git fetch origin $MAIN_BRANCH
          git diff origin/$MAIN_BRANCH...$GITHUB_HEAD_REF

        shell: bash
