name: PR Comparison Workflow

on:
  push:
    branches:
      - test1
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  compare-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display PR branch name
        run: echo "PR branch is ${{ github.head_ref }}"

      - name: Compare code changes
        run: |
          # Assuming the main branch is 'main' (replace with your branch name)
          MAIN_BRANCH="main"
          git checkout $MAIN_BRANCH
          git fetch origin  ${{ github.head_ref }}
          git checkout  ${{ github.head_ref }}
          git diff --name-only \$(git merge-base main  ${{ github.head_ref }})

        shell: bash
