name: PR Comparison Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  compare-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display PR branch name
        run: echo "PR branch is ${{ github.head_ref }}"

      - name: Checkout test2 branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Debug
        run: |
          echo "Current branch: $(git branch)"
          echo "Available branches: $(git branch -a)"
          git remote -v
      # - name: Set Remote URL
      #   run: |
      #     git remote add origin "https://github.com/AnkushDaharwal07/AnkushDaharwal07.git"
      - name: Fetch 'main' and 'test2' branches
        run: |
          git fetch origin main
          git fetch origin ${{ github.head_ref }}
      - name: Run Git Diff
        id: git-diff
        run: |
          # Navigate to the repository directory
          cd $GITHUB_WORKSPACE

          # Run the 'git diff' command comparing the base and head commits of the PR
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- functions.yaml

      - name: Extract Function Name
        id: extract-function-name
        run: |
          # Use 'grep' to find the line containing the function name
          function_line=$(echo "${{ steps.git-diff.outputs.stdout }}" | grep "+  - name:")

          # Extract the function name from the line
          function=$(echo "$function_line" | awk -F': ' '{print $2}')

          # Set the extracted function name as an output
          echo "::set-output name=function::$function"

      - name: Print Extracted Function Name
        run: |
          # Access the extracted function name from the previous step's output
          echo "Extracted Function Name: ${{ steps.extract-function-name.outputs.function }}"
