name: Check YAML Changes

on:
  push:
    branches:
    - main

jobs:
  check_yaml_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GITHUB_REF
        run: echo "GITHUB_REF:${{ github.ref }}"

      - name: Get modified files
        id: modified-files
        run: |
          echo "FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})" >> $GITHUB_ENV
        shell: bash

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        
      - name: Make script executable
        run: chmod +x script.sh

      - name: Run Script
        run: ./script.sh
