name: PR Comparison Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  compare-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display PR branch name
        run: echo "PR branch is ${{ github.head_ref }}"

      - name: Debug
        run: |
          echo "Current branch: $(git branch)"
          echo "Available branches: $(git branch -a)"
          git remote -v
      # - name: Set Remote URL
      #   run: |
      #     git remote add origin "https://github.com/AnkushDaharwal07/AnkushDaharwal07.git"
  
      - name: Compare code changes
        run: |
          # Navigate to the repository directory
          cd $GITHUB_WORKSPACE
          ls
          git  checkout main ;  git checkout test2; git pull origin test2
          git diff $(git merge-base main test2) -- functions.yaml
        
