name: Check YAML Changes

on:
  push:
    branches:
    - test1

jobs:
  check_yaml_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GITHUB_REF
        run: echo "GITHUB_REF:${{ github.ref }}"

      # Add more steps here for processing the YAML changes
