name: PR Comparison Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  compare-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display PR branch name
        run: echo "PR branch is ${{ github.head_ref }}"

      - name: Debug
        run: |
          echo "Current branch: $(git branch)"
          echo "Available branches: $(git branch -a)"

      - name: Get Forked Branch URL
        id: get_forked_url
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          forked_repo_url=$(curl -s -H "Authorization: Bearer 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" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}" \
              | jq -r '.head.repo.clone_url')
          echo "::set-output name=forked_url::${forked_repo_url}"

      - name: Set Remote URL
        run: |
          git remote add forked "${{ steps.get_forked_url.outputs.forked_url }}"
          git remote -v

          
      - name: Fetch 'main' and 'test2' branches
        run: |
          git fetch origin main
          git fetch forked ${{ github.head_ref }}

      - name: Compare code changes
        run: |
          # Navigate to the repository directory
          git diff origin/main..forked/${{ github.head_ref }} -- functions.yaml > extracted_lines2.txt
          cat extracted_lines2.txt

      - name: Extract + - name lines
        id: extract-names
        run: |
          git diff origin/${{ github.base_ref }} forked/${{ github.head_ref }} -- functions.yaml | grep '^\+[[:space:]]*- name:'
          # git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- functions.yaml | grep '^\+[[:space:]]*- name:' > extracted_lines.txt
          git diff origin/${{ github.base_ref }} forked/${{ github.head_ref }} -- functions.yaml | grep '^\+[[:space:]]*- name:' > extracted_lines.txt
        env:
          PYTHONIOENCODING: utf-8

      - name: Display extracted lines
        run: |
          cat extracted_lines.txt
