name: Compare and Process functions.yaml

on:
  pull_request:
    branches:
      - main

jobs:
  compare_and_process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get PR Branch Name
        id: get_pr_branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Run Python Script
        env:
          MAIN_FILE: functions.yaml
          PR_FILE: functions.yaml
        run: |
          # Access the file paths in your Python script
          python script.py "$MAIN_FILE" "$PR_FILE"
