name: Run Script on Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      
      - name: Run Your Python Script
        env:
          MAIN_BRANCH_FILE: functions.yaml
          PR_BRANCH_FILE: functions.yaml
        run: |
          # Copy the main branch file
          cp $MAIN_BRANCH_FILE functions.yaml
          
          # Copy the PR branch file
          cp $PR_BRANCH_FILE functions.yaml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Script
        run: python script.py
