name: Run Script on Push

on:
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
        
      - name: Get PR Branch Name
        id: get_pr_branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

      # - name: Compare functions.yaml
      #   id: compare
      #   run: |
      #     PR_BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
      #     # echo "::set-output name=main_file::functions.yaml"
      #     # echo "::set-output name=pr_file::main:${PR_BRANCH_NAME}/functions.yaml" 
  
      - name: Set Output Variables
        id: set_output_vars
        run: |
          PR_BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "MAIN_FILE=functions.yaml" >> $GITHUB_ENV
          git checkout main
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr${{ github.event.pull_request.head.ref }}
          git checkout pr${{ github.event.pull_request.head.ref }}
          echo "PR_FILE=functions.yaml" >> $GITHUB_ENV
          git checkout main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Python Script
        if: steps.compare.outputs.main_file != '' && steps.compare.outputs.pr_file != ''
        env:
          MAIN_FILE: ${{ steps.compare.outputs.main_file }}
          PR_FILE: ${{ steps.compare.outputs.pr_file }}
        run: |
          # Access the file paths in your Python script
          python scripts/pythonscript.py "$MAIN_FILE" "$PR_FILE"
